services:
  cup:
    labels:
      # Websecure
      # Use the chain-public-auth middleware for domain handling
      traefik.http.routers.cup-rodrigomescua.middlewares: chain-public-auth@file
      # Use the default certresolver
      traefik.http.routers.cup-rodrigomescua.tls.certresolver: ''


