services:
  2fauth:
    labels:
      # Websecure:
      # Use the chain-Domain-auth middleware for domain handling
      traefik.http.routers.2fauth-falkheiland.middlewares: chain-Domain-auth@file
      # Use the default certresolver
      traefik.http.routers.2fauth-falkheiland.tls.certresolver: ''
