services:
  nextcloud-web:
    labels:
      # Websecure
      # Use the chain-Domain middleware for domain handling
      traefik.http.routers.nextcloud-fpm-rodrigomescua.middlewares: chain-Domain@file
      # Use the default certresolver
      traefik.http.routers.nextcloud-fpm-rodrigomescua.tls.certresolver: ''

  nextcloud-db:
    networks:
      # This network is shared with the docker-db-backup app
      shared_docker-db-backup_network:
        gw_priority: 0
    labels:
      cupdate.config.stay-on-current-major: true

networks:
  nextcloud-fpm_rodrigomescua_network:
    external: false
    # Reset to default IPAM configuration to match nextclouds default trusted proxies
    ipam: !reset []
  # This network is shared with the docker-db-backup app
  shared_docker-db-backup_network:
    external: true

