services:
  joplin:
    labels:
      # Websecure
      # Use the chain-public middleware for domain handling
      traefik.http.routers.joplin-rodrigomescua.middlewares: chain-public@file
      # Use the default certresolver
      traefik.http.routers.joplin-rodrigomescua.tls.certresolver: ''

  joplin-db:
    networks:
      # This network is shared with the docker-db-backup app
      shared_docker-db-backup_network:
        gw_priority: 0

networks:
  # This network is shared with the docker-db-backup app
  shared_docker-db-backup_network:
    external: true



