services:
  networking-toolbox:
    labels:
      # Websecure
      # Use the chain-public-auth middleware for domain handling
      traefik.http.routers.networking-toolbox-rodrigomescua.middlewares: chain-public-auth@file
      # Use the default certresolver
      traefik.http.routers.networking-toolbox-rodrigomescua.tls.certresolver: ''
      # WebSecure local IP
      # Use additional router for local access
      traefik.http.routers.networking-toolbox-rodrigomescua-privip.rule: Host(`${APP_DOMAIN}`) && ClientIP(`${PRIVATE_IPV4}`)
      traefik.http.routers.networking-toolbox-rodrigomescua-privip.middlewares: chain-public@file
      traefik.http.routers.networking-toolbox-rodrigomescua-privip.entrypoints: websecure
      traefik.http.routers.networking-toolbox-rodrigomescua-privip.service: networking-toolbox-rodrigomescua
      traefik.http.routers.networking-toolbox-rodrigomescua-privip.priority: 100
      traefik.http.routers.networking-toolbox-rodrigomescua-privip.tls.certresolver: ''


