services:
  metube:
    labels:
      # Websecure
      # Use the chain-public-auth middleware for domain handling
      traefik.http.routers.metube-rodrigomescua.middlewares: chain-public-auth@file
      # Use the default certresolver
      traefik.http.routers.metube-rodrigomescua.tls.certresolver: ''


