services:
  freshrss:
    labels:
      # Websecure
      # Use the chain-Domain-auth middleware for domain handling
      traefik.http.routers.freshrss-oidc-rodrigomescua.middlewares: chain-Domain-auth@file
      # Use the default certresolver
      traefik.http.routers.freshrss-oidc-rodrigomescua.tls.certresolver: ''

