services:
  2fauth:
    labels:
      # Websecure:
      # Use the chain-public-auth middleware for domain handling
      traefik.http.routers.2fauth-rodrigomescua.middlewares: chain-public-auth@file
      # Use the default certresolver
      traefik.http.routers.2fauth-rodrigomescua.tls.certresolver: ''


