services:
  pinchflat:
    labels:
      # Websecure
      # Use the chain-public-auth middleware for domain handling
      traefik.http.routers.pinchflat-rodrigomescua.middlewares: chain-public-auth@file
      # Use the default certresolver
      traefik.http.routers.pinchflat-rodrigomescua.tls.certresolver: ''


